### ISSUE TITLE
Scripts for remote Rig Power-On/Off

### ISSUE THREAD

**Issue by WheezyE** [km4ack/pi-scripts#19]
I've been playing with hamlib/rigctl's functions for turning my FT-891 on/off from the command line.  This feature only works with some radios, so it wouldn't be for every user.  But the ability to turn on/off your rig from the pi would enable:
1. Putting the rig and all components/batteries/etc into a Pelican case (or harbor freight Apache case) and never having to open the case to operate the rig (ie in the rain, from the back seat of the truck, from a hidden-away cupboard in your home, etc).
 - You could even go the extra mile and put a separation kit in the case to allow you to plug your hand mic directly into the side of the Pelican case.
 - That way, you'd just have power hookup (or battery power switch) on the outside of the case (which would boot the pi), antenna hookup to the outside of the case, and handmic hookup to the outside of the case.
2. Remote operation of digital signals (via remoting into your home computer where your rig is located from anywhere in the world with an internet connection - via Chrome Remote Desktop or likewise).

I created this pastebin with my research https://pastebin.com/F9i7HXdJ . Feel free to use any/all of it in your pi scripts/build (future work would be a function to echo to the user that 1. the pi is attempting to turn on or off the radio for a few seconds. 2. That the radio is now on or off. Future work may also be possibly to run the radio turn on command at Pi startup and the radio turn off command on Pi shutdown).

**Comment by WheezyE** [comment]
Update: This may not be an option for the FT-857d.  Its CAT control documentation doesn't include a power on/off command, and the [hamlib sourcecode comments](https://github.com/Hamlib/Hamlib/blob/master/rigs/yaesu/ft857.c) seem to think it doesn't work.  This should work for the FT-817 though, though the power on/off behavior is said to be different depending on if the 817 is on battery power or not.

However, the 857d does allow power on/off from the handmic ([from pin 3 on the handmic's RJ12 jack](https://github.com/tomelec/ft-857_front_panel_protocol/blob/master/doc/hardware.md)).  You could still put an RJ12 6P6C socket on the side of a Pelican case (with an extension cable plugging into the handmic socket on the 857d's front panel) and then hook the handmic into the outside of the closed Pelican case.

**Comment by km4ack** [comment]
You sir are always pushing the limits! I like it. And I recently acquired an 891. Currently buried in another project. I could use some help testing. Shoot me an email mycall@arrl.net if you're interested.

**Comment by km4ack** [comment]
I needed a break from the other project. This is what I came up with in about 20 minutes. [891 Control](https://github.com/km4ack/pi-scripts/blob/master/891control)

**Comment by WheezyE** [comment]
Very nicely done!  I'll send you email
